export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCTS_BY_CAT = 'SET_PRODUCTS_BY_CAT';
export const GET_TOTAL = 'GET_TOTAL';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PRODUCTS_BY_ID = 'SET_PRODUCTS_BY_ID';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_TO_CART = 'DELETE_PRODUCT_TO_CART';
export const MINUS_ITEM_FROM_CART = 'MINUS_ITEM_FROM_CART';
export const PLUS_ITEM_FROM_CART = 'PLUS_ITEM_FROM_CART';
export const GET_ALL_WITHOUT_ANY_CONDITION = 'GET_ALL_WITHOUT_ANY_CONDITION';
export const SET_PRODUCT_COUNT = 'SET_PRODUCT_COUNT';
export const SET_ALL_PRODUCT = 'SET_ALL_PRODUCT';